name = input("Enter a Name: ")
adjective = input("Enter a Adjective: ")
adjective2 = input("Enter a Adjective:")
adverb = input("Enter a adverb: ")
food = input("Enter a Food: ")
food2 = input("Enter Another Food: ")
noun = input("Enter a noun: ")
place = input("Enter a Place: ")
verb = input("Enter a Verb: ")
print("Let's play Silly Sentances!")
print( name + "was planning a dream vacation to " + place)
print( name + "was especially looking forward to trying the local cuisine, including  " + adjective  +  food  + " and " +  food2)
print( name + "will have to practice the language " + adverb + "to make it easier to " +verb + " with people")
print( name + "has a long list of sights to see, including the " + noun + "museum and the " + adjective2 + "park.")